// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    TimeSchedule: typeof import('./src/components/TimeSchedule.vue')['default']
    TimezoneItem: typeof import('./src/components/TimezoneItem.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}
